version: 1.0.{build}
build:
  project: src\FastSms.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
  
build_script:
  - "echo APPVEYOR: %APPVEYOR%"
  - "echo APPVEYOR_REPO_TAG: %APPVEYOR_REPO_TAG%"
  - "echo APPVEYOR_REPO_BRANCH: %APPVEYOR_REPO_BRANCH%"
  
after_build:
- nuget pack src\FastSms\FastSms.csproj  -Version "%APPVEYOR_BUILD_VERSION%"

test:
  categories:
    only:
    - Unit

artifacts:
- path: '*.nupkg'
  name: TestAppVeyor
install:
  - nuget restore src\FastSms.sln
  - nuget install Moq -Version 4.1.1309.1617 -OutputDirectory tests\FastSms.Tests

deploy:
  provider: NuGet
  api_key: fa0bd176-3bdd-49d9-afd1-635b1965fa13
  artifact: TestAppVeyor
  on:
    branch: task_codereview
	appveyor_repo_tag: true
  
